# Generated by Django 4.2 on 2024-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0018_remove_certification_objectif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='criteres',
            field=models.TextField(default=''),
        ),
    ]
