# Generated by Django 4.2 on 2024-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0019_certification_criteres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='numberOfQuestions',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='passingScore',
        ),
        migrations.AddField(
            model_name='exam',
            name='numberOfQuestions',
            field=models.IntegerField(default=30),
        ),
    ]
